### ISSUE TITLE
Trivial Bug Report: Clicking story after search requires 2 clicks

### ISSUE THREAD

**Issue by luckman212** [pcr910303/HackerNews#10]
Thanks @goranmoomin for this wonderful app! It's extremely fast. 🚀 

One thing I noticed is it takes 2 clicks to open a story after running a search. The middle pane sort of reloads/refreshes upon the first click. The 2nd click triggers the story load.  I made a screen recording:

https://user-images.githubusercontent.com/1992842/127867501-554c0e38-1d3d-4d78-b702-26c5ef53dd56.mp4

**Comment by goranmoomin** [comment]
Oh, yeah I could reproduce it. I'll try to look into it and fix it in the next release.

**Comment by goranmoomin** [comment]
I've pushed a fix to the main branch, the fix will be applied in the next release.
Thanks for the report!

**Comment by luckman212** [comment]
Awesome, looks good - will try it out once the build shows up

**Comment by goranmoomin** [comment]
Sorry for the long, long delay... I've just added a new release that has the fix! Let me know if it still doesn't work.
