### ISSUE TITLE
something like <cloud> in a comment causes the text to disappear

### ISSUE THREAD

**Issue by luckman212** [pcr910303/HackerNews#14]
Just noticed this,
e.g. https://news.ycombinator.com/item?id=30066602

**Safari:**
![CleanShot 2022-01-24 at 20 49 41](https://user-images.githubusercontent.com/1992842/150895723-9d19c926-11c1-4ad3-8bf7-287672ef1aad.png)

**HackerNews:**
![CleanShot 2022-01-24 at 20 48 55](https://user-images.githubusercontent.com/1992842/150895681-31fdd542-0af2-43f3-b6e1-3a417c2850bd.png)

**Comment by goranmoomin** [comment]
So for some reason the GitHub app's notifications are wary and I keep losing them. I'll take a look into this ASAP. Looks like a simple escaping bug...

**Comment by goranmoomin** [comment]
v0.1.3 should hopefully have this fixed. Let me know if it still doesn't work!
