### ISSUE TITLE
Feature: Add a keyboard shortcut (⌘+R) for refresh

### ISSUE THREAD

**Issue by AlexanderWillner** [pcr910303/HackerNews#3]
See subject.

**Comment by brandongalbraith** [comment]
Having an option in preferences to auto refresh at an interval would also be welcome (no faster than say, every 5 minutes).

**Comment by goranmoomin** [comment]
I've just implemented it in main - the app will have <kbd>Cmd+R</kbd>  for refreshing the page and <kbd>Cmd+Shift+R</kbd> for refreshing the article list next release.

**Comment by goranmoomin** [comment]
I've just released [v0.1.1](https://github.com/goranmoomin/HackerNews/releases/tag/v0.1.1) with this resolved.

If there are any problems, please comment and tag me. Thanks!
