### ISSUE TITLE
Feature: Add keyboard navigation

### ISSUE THREAD

**Issue by dbuskariol** [pcr910303/HackerNews#5]
It would be really nice if you could navigate between stories and comments using the keyboard arrow keys.

**Comment by goranmoomin** [comment]
I've just implemented it in main - the app will have keyboard arrow key navigation between the sidebar, stories, and comments in the next release.

**Comment by goranmoomin** [comment]
I've just released [v0.1.1](https://github.com/goranmoomin/HackerNews/releases/tag/v0.1.1) with this resolved.

If there are any problems, please comment and tag me. Thanks!
