### ISSUE TITLE
Feature: Preference to set nested comments to auto expand

### ISSUE THREAD

**Issue by dbuskariol** [pcr910303/HackerNews#6]
Clicking the small arrow to expand child comments for a particular parent comment is cumbersome. I'd like all comments to always be expanded. Additionally it would be nice if you could toggle this behavior with a keyboard shortcut.

**Comment by goranmoomin** [comment]
I've pushed a commit to main to make the comments to be expanded by default. The next release will auto-expand the comments.

> Additionally it would be nice if you could toggle this behavior with a keyboard shortcut.

A tip: In most Cocoa apps, you can option-click the disclosure triangle to recursively open/close a tree.

**Comment by goranmoomin** [comment]
I've just released [v0.1.1](https://github.com/goranmoomin/HackerNews/releases/tag/v0.1.1) with this resolved.

If there are any problems, please comment and tag me. Thanks!
